apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-operator
  namespace: kv-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kv-operator
  template:
    metadata:
      labels:
        app: kv-operator
    spec:
      serviceAccountName: kv-operator
      containers:
      - name: operator
        image: varn03/kv-operator:latest
        env:
        - name: CONTROLLER_ADDR
          value: "http://controller.kv-system.svc.cluster.local:8000"
