apiVersion: v1
kind: Service
metadata:
  name: worker3
  namespace: kv-system
spec:
  selector:
    app: worker3
  ports:
    - name: http
      port: 8001
      targetPort: 8001
    - name: grpc
      port: 50051
      targetPort: 50051
