apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker2
  namespace: kv-system
  labels:
    app: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2
  template:
    metadata:
      labels:
        app: worker2
    spec:
      containers:
      - name: worker
        image: varn03/kv-worker:latest
        env:
          - name: NODE_ID
            value: "worker2"
          - name: CONTROLLER_ADDR
            value: "http://controller.kv-system.svc.cluster.local:8000"
          - name: REDIS_URL
            value: "redis://redis.kv-system.svc.cluster.local:6379/0"
          - name: MONGO_URL
            value: "mongodb://worker2-mongo:27017"
          - name: GRPC_PORT
            value: "50051"
          - name: HTTP_PORT
            value: "8001"
        ports:
          - containerPort: 8001
          - containerPort: 50051
