apiVersion: v1
kind: Service
metadata:
  name: workers-headless
  namespace: kv-system
spec:
  clusterIP: None
  selector:
    app: worker  # not used directly unless you label workers with app: worker
  ports:
    - name: http
      port: 8001
    - name: grpc
      port: 50051
